before:
  hooks:
    - go mod tidy
builds:
  - flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    ldflags: |
      -s -w -extldflags '-static'
    goos:
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - src: dist/CHANGELOG.md
        dst: ""
        strip_parent: true
checksum:
  disable: true
snapshot:
  name_template: "{{ .Tag }}-next"
nfpms:
  - package_name: pktstat
    vendor: Dinko Korunic
    homepage: https://github.com/dkorunic/pktstat
    maintainer: Dinko Korunic <dkorunic@gmail.com>
    description: Ethernet interface traffic monitor
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    bindir: /usr/bin
    section: net
    priority: optional
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
