before:
  hooks:
    - go mod tidy
builds:
  - flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    ldflags: |
      -s -w -extldflags '-static'
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
universal_binaries:
  - replace: true
changelog:
  sort: asc
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - src: dist/CHANGELOG.md
        dst: ""
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
nfpms:
  - package_name: axfr2hosts
    vendor: Dinko Korunic
    homepage: https://github.com/dkorunic/axfr2hosts
    maintainer: Dinko Korunic <dkorunic@gmail.com>
    description: Fetches one or more DNS zones via AXFR and dumps in Unix hosts format for local use
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    bindir: /usr/bin
    section: net
    priority: optional
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
